version: '3.8'

services:
  custom-mysql:
    hostname: postgres
    image: postgres
    container_name: test-postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test_db
    networks:
      - my_network
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:

networks:
  my_network: